/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class App {
  constructor()
  static withCli(cli: boolean): App
  run(): Promise<void>
  transform(callback: (input: any) => any): void
  validate(name: string, callback: (...args: any[]) => any): void
  callback(name: string, callback: (...args: any[]) => any): void
  compare(name: string, callback: (...args: any[]) => any): void
}
