/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Namespace {
  definePipelineItem(name: string, body: (args: {[key: string]: any}, ctx?: any) => any | Promise<any>): void
}
export class ObjectId { }
export class DateOnly { }
export class Range { }
export class File { }
export class EnumVariant { }
export class OptionVariant { }
export class Pipeline { }
export class InterfaceEnumVariant { }
export class App {
  /** Create a Teo app. */
  constructor()
  /** @internal */
  static withCli(cli: boolean): App
  /** Run this app. */
  run(): Promise<void>
  mainNamespace(): Namespace
}
